export const UPDATE_FOO = 'UPDATE_FOO';

export const INITIALISE_STORE = 'INITIALISE_STORE'

export const SET_EXTENSIONS_STATE = 'SET_EXTENSIONS_STATE'

export const ADD_PROJECT = 'ADD_PROJECT'

export const REMOVE_PROJECT = 'REMOVE_PROJECT'

export const TOGGLE_PROJECT = 'TOGGLE_PROJECT'

export const REMOVE_MEMBER = 'REMOVE_MEMBER'

export const SET_MEMBER_PROP = 'SET_MEMBER_PROP'

export const ADD_MEMBER_IN_PROJECT = 'ADD_MEMBER_IN_PROJECT'

export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION'

export const SET_MEMBERS_STATUS = 'SET_MEMBERS_STATUS'
